description: HH-suite3 for sensitive sequence searching
long_description: The HH-suite is an open-source software package for sensitive protein sequence searching based on the pairwise alignment of hidden Markov models (HMMs).
homepage_url: https://github.com/soedinglab/hh-suite
name: hhsuite
owner: guerler
